---
title: "Research Proposal"
subtitle: "Measuring Food Waste in Prince George Restaurant:\ Volume, Model, and Effects"
author: "Akihiko Mori, MA NRES UNBC"
date: "January 01, 2023"
output: 
  beamer_presentation:
    slide_level: 2
    toc: true
    theme: "Berkeley"
    colortheme: "whale"
    fonttheme: "structurebold"
    incremental: false
header-includes: 
- \definecolor{unbc}{HTML}{035642}
- \setbeamercolor{structure}{fg=unbc}
- \setbeamertemplate{navigation symbols}{}
- \setbeamertemplate{footline}[page number]
#- \pgfdeclareimage[height=.5cm]{logoUNBC}{~/Library/CloudStorage/OneDrive-UNBC/00MAthesis/maRcode/maRcode/Official-UNBC-Logo/Green UNBC Logo/logo_green.tif}
#- \logo{\pgfuseimage{logoUNBC}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
## Introduction
<!-- World -->
- Bullet 1

<!-- Canada -->
- Bullet 2
- Bullet 3

<!-- BC -->
- Bullet 2
- Bullet 3

<!-- PG -->
- Bullet 2
- Bullet 3

<!-- Food Service -->
- Bullet 2
- Bullet 3

## Introduction
### Objectives

- What is the average volume of food that is wasted during processing and consumption in restaurants?
- What is the extent of food wastage in Japanese restaurants in Prince George?
- What are the main factors contributing to food loss and waste?
- To what extent is a social or environmental impact from food loss waste generated by a
single restaurant?
- What approaches are Japanese restaurant operators taking to reduce food waste generation?

## Introduction
### Significance

- Bullet 1
- Bullet 2
- Bullet 3


# Literature Review
## Literature Review

### Definition of Food Loss and Waste

- Bullet 1
- Bullet 2
- Bullet 3

## Literature Review
### Measurements of Food Loss and Waste

- Bullet 1
- Bullet 2
- Bullet 3

## Literature Review
### Statistic Model

- Bullet 1
- Bullet 2
- Bullet 3

## Literature Review
### Effects of Food Loss and Waste

- Bullet 1
- Bullet 2
- Bullet 3

## Literature Review
## Hypotheses

- Bullet 1
- Bullet 2
- Bullet 3


# Methods
## Methods
### Sample Collection
- Bullet 1
- Bullet 2
- Bullet 3

## Methods
### Sample Size
- Bullet 1
- Bullet 2
- Bullet 3

## Methods
### Variables
- Bullet 1
- Bullet 2
- Bullet 3

## Methods
### Model
- Bullet 1
- Bullet 2
- Bullet 3



# Expected Results
## Expected Results

### Current Progress

- Bullet 1
- Bullet 2
- Bullet 3


# References

